name = "notion-stockprices"
type = "javascript"

account_id = ""
workers_dev = true
compatibility_date = "2022-04-07"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[vars]
NOTION_TOKEN = ""
NOTION_DATABASE_ID = ""
FINNHUB_TOKEN = ""

[triggers]
crons = ["*/15 14-20 * * 2-6"]